name: Lint Files

on:
  push:
    branches:
      - '*'

jobs:
  lint-server:
    name: Lint App
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the repository
        uses: actions/checkout@v1
      - name: Use NodeJS ${{ matrix.node-version }}
        uses: actions/setup-node@v2
        with:
          node-version: 16
          registry-url: https://registry.npmjs.org/
      - name: Install Dependencies and lint
        run: |
          npm install
          npm run lint
