name: Lint Files

on:
  push:
    branches-ignore:
      - master

jobs:
  lint-server:
    name: Lint App
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the repository
        uses: actions/checkout@v6
      - name: Use NodeJS ${{ matrix.node-version }}
        uses: actions/setup-node@v6
        with:
          node-version: 24
          registry-url: https://registry.npmjs.org/
      - name: Install Dependencies and lint
        run: |
          npm install
          npm run lint
