# This workflow will publish a NodeJS package to npm when a release is created

name: Publish to NPM

on:
  release:
    types: [published]

jobs:
  publish-npm:
    if: github.event.release.target_commitish == 'master'
    runs-on: ubuntu-latest
    permissions:
      contents: read
      id-token: write
    steps:
      - name: Checkout the repository
        uses: actions/checkout@v3
        with:
          ref: ${{ github.event.release.tag_name }}

      # Use Node v20 (latest than v16) when publishing with provenance
      - name: Use NodeJS v20.15.0
        uses: actions/setup-node@v3
        with:
          node-version: 20.15.0
          registry-url: https://registry.npmjs.org/

      - name: Publish package
        run: npm publish --provenance --access public
        env:
          NODE_AUTH_TOKEN: ${{secrets.NPM_TOKEN}}
